/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponentWrapper: typeof import('./components/AsyncComponentWrapper.vue')['default']
    CacheControls: typeof import('./components/CacheControls.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DropList: typeof import('./components/DropList.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FooterDropDownInfo: typeof import('./components/footer/FooterDropDownInfo.vue')['default']
    Form: typeof import('./components/form/Form.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Mandala: typeof import('./components/Mandala.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundButton: typeof import('./components/SoundButton.vue')['default']
    SWCrawlText: typeof import('./components/SWCrawlText.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
