/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponentWrapper: typeof import('./components/AsyncComponentWrapper.vue')['default']
    CacheControls: typeof import('./components/CacheControls.vue')['default']
    Dialog: typeof import('./components/AppDialog.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FooterDropDownInfo: typeof import('./components/footer/FooterDropDownInfo.vue')['default']
    Form: typeof import('./components/form/Form.vue')['default']
    FormControls: typeof import('./components/FormControls.vue')['default']
    Link: typeof import('./components/AppLink.vue')['default']
    Logo: typeof import('./components/AppLogo.vue')['default']
    Mandala: typeof import('./components/AppMandala.vue')['default']
    ResultDisplay: typeof import('./components/ResultDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchField: typeof import('./components/SearchField.vue')['default']
    SoundButton: typeof import('./components/SoundButton.vue')['default']
    SWCrawlText: typeof import('./components/SWCrawlText.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
